services:
  web:
    build:
      context: docker/web/.
    restart: unless-stopped
    expose:
      - '80'
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html

  composer:
    image: composer
    profiles: [ 'dev' ]
    volumes:
      - .:/app

  node:
    image: node:lts-alpine
    profiles: [ 'dev' ]
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
