name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Markdown
      uses: articulate/actions-markdownlint@v1
      with:
        files: '**/*.md'
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        path: "bin/"
